sql-scheduler:
    queryLogsDirectory: query-logs
    
    triggers:
      #Every 3 seconds
      - '*/3 * * * * *' 
      #Every day at 19:54
      - '0 54 19 * * ?'
      #On the hour nine-to-five weekdays
      - "0 0 9-17 * * MON-FRI"
    queries:          
      - statement: "SELECT 1"
        resultFile: "select-1.txt"
     
      - statement: "SELECT 2"